Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2020-09, with the labels that each got.

#8 generate clientsets, informers and listers since keda 1.5.0 does not do it
  hack/keda-doc.go
  hack/keda-register.go
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_keda_client.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_scaledjob.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_scaledobject.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_triggerauthentication.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/keda_client.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/scaledjob.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/scaledobject.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/triggerauthentication.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/keda/interface.go
  pkg/client/informers/externalversions/keda/v1alpha1/interface.go
  pkg/client/informers/externalversions/keda/v1alpha1/scaledjob.go
  pkg/client/informers/externalversions/keda/v1alpha1/scaledobject.go
  pkg/client/informers/externalversions/keda/v1alpha1/triggerauthentication.go
  pkg/client/listers/keda/v1alpha1/expansion_generated.go
  pkg/client/listers/keda/v1alpha1/scaledjob.go
  pkg/client/listers/keda/v1alpha1/scaledobject.go
  pkg/client/listers/keda/v1alpha1/triggerauthentication.go
Labels: approved, cla: yes, lgtm, size/M

#10 Add linting config and fix issues.
  .golangci.yaml
  hack/keda-register.gopatch
  hack/update-codegen.sh
  pkg/reconciler/crd/controller.go
Labels: approved, cla: yes, lgtm, size/S

#11 remove unnecessary clients
  hack/keda-doc.go
  hack/keda-register.gopatch
  hack/update-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_keda_client.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_scaledjob.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_scaledobject.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/fake/fake_triggerauthentication.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/keda_client.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/scaledjob.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/scaledobject.go
  pkg/client/clientset/versioned/typed/keda/v1alpha1/triggerauthentication.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/keda/interface.go
  pkg/client/informers/externalversions/keda/v1alpha1/interface.go
  pkg/client/informers/externalversions/keda/v1alpha1/scaledjob.go
  pkg/client/informers/externalversions/keda/v1alpha1/scaledobject.go
  pkg/client/informers/externalversions/keda/v1alpha1/triggerauthentication.go
  pkg/client/listers/keda/v1alpha1/expansion_generated.go
  pkg/client/listers/keda/v1alpha1/scaledjob.go
  pkg/client/listers/keda/v1alpha1/scaledobject.go
  pkg/client/listers/keda/v1alpha1/triggerauthentication.go
Labels: approved, cla: yes, lgtm, size/M

#12 fix typo: kedav1aplha1 => kedav1alpha1
  pkg/reconciler/awssqs/awssqs.go
  pkg/reconciler/kafka/kafka.go
  pkg/reconciler/keda/resources.go
  pkg/reconciler/source/source.go
Labels: approved, cla: yes, lgtm, size/S

#13 Pkg update
  go.mod
  go.sum
  pkg/reconciler/source/controller.go
  third_party/VENDOR-LICENSE/github.com/gobuffalo/envy/LICENSE
  third_party/VENDOR-LICENSE/github.com/gobuffalo/envy/LICENSE.txt
  third_party/VENDOR-LICENSE/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/gobuffalo/envy/.gitignore
  vendor/github.com/gobuffalo/envy/.gometalinter.json
  vendor/github.com/gobuffalo/envy/.travis.yml
  vendor/github.com/gobuffalo/envy/LICENSE
  vendor/github.com/gobuffalo/envy/Makefile
  vendor/github.com/gobuffalo/envy/azure-pipelines.yml
  vendor/github.com/gobuffalo/envy/azure-tests.yml
  vendor/github.com/gobuffalo/envy/azure.sh
  vendor/github.com/gobuffalo/envy/env
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/go.mod
  vendor/github.com/gobuffalo/envy/go.sum
  vendor/github.com/gobuffalo/envy/shoulders.md
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/modfile/gopkgin.go
  vendor/github.com/rogpeppe/go-internal/modfile/print.go
  vendor/github.com/rogpeppe/go-internal/modfile/read.go
  vendor/github.com/rogpeppe/go-internal/modfile/rule.go
  vendor/github.com/rogpeppe/go-internal/module/module.go
  vendor/github.com/rogpeppe/go-internal/semver/semver.go
  vendor/knative.dev/pkg/apis/duck/cached.go
  vendor/knative.dev/pkg/apis/duck/enqueue.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#14 update deps, use logging from knative.dev/pkg
  go.mod
  go.sum
  pkg/reconciler/source/source.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/stats/view/aggregation.go
  vendor/go.opencensus.io/stats/view/aggregation_data.go
  vendor/go.opencensus.io/stats/view/collector.go
  vendor/go.opencensus.io/stats/view/view_to_metric.go
  vendor/go.opencensus.io/stats/view/worker.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/analysisinternal/analysis.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/lsp/fuzzy/input.go
  vendor/golang.org/x/tools/internal/lsp/fuzzy/matcher.go
  vendor/honnef.co/go/tools/pattern/match.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/honnef.co/go/tools/version/version.go
  vendor/knative.dev/eventing-contrib/kafka/source/pkg/apis/sources/v1beta1/kafka_lifecycle.go
  vendor/knative.dev/eventing/pkg/logging/logging.go
  vendor/knative.dev/eventing/pkg/utils/headers.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#18 enable code coverage
  .codecov.yaml
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/M

#17 plumb broker annotations through, add docs
  README.md
  go.mod
  pkg/reconciler/broker/broker.go
  pkg/reconciler/keda/annotations.go
  pkg/reconciler/trigger/resources/scaled_object.go
  pkg/reconciler/trigger/trigger.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#20 remove finalizekind
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/S
