Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2020-11, with the labels that each got.

#37 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#38 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#40 Redisstream Source initial support
  README.md
  go.mod
  go.sum
  pkg/reconciler/keda/annotations.go
  pkg/reconciler/keda/resources.go
  pkg/reconciler/redisstream/redisstream.go
  pkg/reconciler/source/source.go
  pkg/reconciler/trigger/trigger.go
  samples/redisstream-source.yaml
  third_party/VENDOR-LICENSE/knative.dev/eventing-redis/source/pkg/apis/sources/LICENSE
  vendor/knative.dev/eventing-redis/LICENSE
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/register.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/redisstream_lifecycle.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/redisstream_types.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#29 Scale KafkaSource CRD instead of the receive adapter
  pkg/reconciler/awssqs/awssqs.go
  pkg/reconciler/kafka/kafka.go
  pkg/reconciler/keda/resources.go
  pkg/reconciler/source/source.go
Labels: approved, cla: yes, lgtm, size/S

#42 bug fix for supporting SASL and TLS
  pkg/reconciler/kafka/kafka.go
Labels: approved, cla: yes, lgtm, size/XS

#44 fix: use GenerateScaleTarget in redisstream reconciler
  pkg/reconciler/redisstream/redisstream.go
  pkg/reconciler/source/source.go
Labels: approved, cla: yes, lgtm, size/S

#49 make tls certificates optional
  pkg/reconciler/kafka/kafka.go
  pkg/reconciler/source/source.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#43 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S

#50 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
