Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2020-12, with the labels that each got.

#53 Scale RedisStreamSource resource instead of deployment
  pkg/reconciler/redisstream/redisstream.go
  pkg/reconciler/source/source.go
  samples/kafka-source.yaml
  samples/redisstream-source.yaml
Labels: approved, cla: yes, lgtm, size/M

#55 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1beta1/kafka_lifecycle.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1beta1/kafka_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/bindings/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/redisstream_lifecycle.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/redisstream_types.go
  vendor/knative.dev/eventing-redis/source/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#57 fix wrong comment about RabbitMQ
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#59 Integrate the gopath hacks
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/M
