Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-04, with the labels that each got.

#112 Update deps for 0.22 release
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#119 Kafka: propagate sasl type
  pkg/reconciler/kafka/kafka.go
Labels: approved, cla: yes, lgtm, size/S

#118 Improve Source Reconcile loop
  go.sum
  pkg/reconciler/crd/controller.go
  pkg/reconciler/crd/reconciler.go
  pkg/reconciler/source/source.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1beta1/customresourcedefinition/customresourcedefinition.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#120 don't reconcile on updates on ScaledObject.Status
  pkg/reconciler/source/controller.go
Labels: approved, cla: yes, lgtm, size/S

#117 Minor samples & readme fixes
  README.md
  samples/kafka-source.yaml
  samples/kafka-topic.yaml
Labels: approved, cla: yes, lgtm, size/XS

#121 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/context.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#123 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#124 Make name more meaningful
  config/controller.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
