Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-06, with the labels that each got.

#140 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#141 bump KEDA dep to 2.3.0
  go.mod
  go.sum
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/container/apiv1/gapic_metadata.json
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/cloud.google.com/go/trace/apiv2/gapic_metadata.json
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/google.golang.org/api/option/option.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/http.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/resource.pb.go
  vendor/google.golang.org/genproto/googleapis/api/distribution/distribution.pb.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/googleapis/api/label/label.pb.go
  vendor/google.golang.org/genproto/googleapis/api/launch_stage.pb.go
  vendor/google.golang.org/genproto/googleapis/api/metric/metric.pb.go
  vendor/google.golang.org/genproto/googleapis/api/monitoredres/monitored_resource.pb.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#143 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#145 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#147 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#150 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ztypes_dragonfly_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_mips64.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#152 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/kafka/v1alpha1/reset_offset_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
