Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-03, with the labels that each got.

#90 fix codeowners
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#89 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#91 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_combined_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  vendor/knative.dev/eventing-kafka/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/configs/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_defaults.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/configs/v1alpha1/configmappropagation.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/configs/v1alpha1/configs_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/configs/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/configs/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/configs/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/configs/v1alpha1/configmappropagation.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/configs/v1alpha1/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/generic.go
  vendor/knative.dev/eventing/pkg/client/listers/configs/v1alpha1/configmappropagation.go
  vendor/knative.dev/eventing/pkg/client/listers/configs/v1alpha1/expansion_generated.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/keda/client/client.go
  pkg/client/injection/keda/client/fake/fake.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_defaults.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_validation.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#94 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing-kafka/pkg/apis/sources/v1beta1/kafka_types.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#98 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#106 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#104 Fix deployment securityContext to use "65532" user
  config/200-clusterrole.yaml
  config/controller.yaml
Labels: approved, cla: yes, lgtm, size/S

#105 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S

#107 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#108 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#111 [Automated] Format markdown
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#110 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/test/rekt/resources/svc/service.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/execution.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/timings.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
