Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-01, with the labels that each got.

#60 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#62 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#64 Updates
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#66 Add release script
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#69 Fix release.sh permissions
  hack/release.sh
Labels: approved, cla: yes, lgtm

#70 Fix permissions on release.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#68 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#71 do not vendor license classifier
  go.mod
  go.sum
  hack/tools.go
  vendor/github.com/google/licenseclassifier/.travis.yml
  vendor/github.com/google/licenseclassifier/CHANGELOG
  vendor/github.com/google/licenseclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/README.md
  vendor/github.com/google/licenseclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/file_system_resources.go
  vendor/github.com/google/licenseclassifier/forbidden.go
  vendor/github.com/google/licenseclassifier/go.mod
  vendor/github.com/google/licenseclassifier/go.sum
  vendor/github.com/google/licenseclassifier/internal/sets/sets.go
  vendor/github.com/google/licenseclassifier/internal/sets/stringset.go
  vendor/github.com/google/licenseclassifier/license_type.go
  vendor/github.com/google/licenseclassifier/stringclassifier/CONTRIBUTING.md
  vendor/github.com/google/licenseclassifier/stringclassifier/LICENSE
  vendor/github.com/google/licenseclassifier/stringclassifier/README.md
  vendor/github.com/google/licenseclassifier/stringclassifier/classifier.go
  vendor/github.com/google/licenseclassifier/stringclassifier/internal/pq/priority.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/searchset.go
  vendor/github.com/google/licenseclassifier/stringclassifier/searchset/tokenizer/tokenizer.go
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/operation_string.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#73 Manual upgrade to float the deps since automation is failing
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/host.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  vendor/knative.dev/eventing/pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  vendor/knative.dev/eventing/pkg/client/listers/configs/v1alpha1/configmappropagation.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1/broker.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1/trigger.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta1/broker.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta1/eventtype.go
  vendor/knative.dev/eventing/pkg/client/listers/eventing/v1beta1/trigger.go
  vendor/knative.dev/eventing/pkg/client/listers/flows/v1/parallel.go
  vendor/knative.dev/eventing/pkg/client/listers/flows/v1/sequence.go
  vendor/knative.dev/eventing/pkg/client/listers/flows/v1beta1/parallel.go
  vendor/knative.dev/eventing/pkg/client/listers/flows/v1beta1/sequence.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1/channel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1/subscription.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/channel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/listers/messaging/v1beta1/subscription.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1/containersource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/containersource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1alpha2/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta1/containersource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/listers/sources/v1beta2/pingsource.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
