Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-11, with the labels that each got.

#205 Document maturity levels in sandbox
  README.md
Labels: approved, size/XS, lgtm, cla: yes

#204 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#207 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm, cla: yes

#208 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, size/M, lgtm, cla: yes

#206 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#210 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes
