Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2021-08, with the labels that each got.

#163 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#166 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm, cla: yes

#167 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing-kafka/pkg/apis/messaging/v1beta1/kafka_channel_defaults.go
  vendor/knative.dev/eventing-kafka/test/rekt/features/kafkasource/data_plane.go
  vendor/knative.dev/eventing-kafka/test/rekt/features/kafkasource/mt_data_plane.go
  vendor/knative.dev/eventing-kafka/test/rekt/features/kafkasource/readiness.go
  vendor/knative.dev/eventing-kafka/test/rekt/resources/kafkacat/kafkacat.go
  vendor/knative.dev/eventing-kafka/test/rekt/resources/kafkasource/kafkasource.go
  vendor/knative.dev/eventing-kafka/test/rekt/resources/kafkatopic/topic.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#168 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#170 [main] Format Go code
  hack/tools.go
  test/e2e/main_test.go
  test/e2e/smoke_test.go
Labels: approved, size/XS, lgtm, cla: yes

#173 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm, cla: yes

#174 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#176 Use `controller.NewContext`
  pkg/reconciler/source/controller.go
Labels: approved, size/XS, kind/cleanup, lgtm, cla: yes

#178 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/golang.org/x/net/http2/README
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/sts_exchange.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/urlcredsource.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/binarylog/sink.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, cla: yes

#179 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, cla: yes

#181 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, cla: yes
