Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2022-05, with the labels that each got.

#283 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#284 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#288 Retrieve SASL type from secretKeyRef in Kafka Source
  pkg/reconciler/kafka/kafka.go
  pkg/reconciler/source/source.go
Labels: approved, size/M, kind/bug, lgtm

#287 update rabbitmq queue name to match eventing-rabbitmq
  pkg/reconciler/trigger/resources/scaled_object.go
Labels: approved, size/XS, kind/bug, lgtm

#290 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#291 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#292 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#293 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#295 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#296 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/M, lgtm
