Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2022-08, with the labels that each got.

#312 use go 1.18
  go.mod
  go.sum
Labels: approved, size/L, lgtm

#313 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#314 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#315 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#316 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#317 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#318 use go 1.18 to run tests
  .github/workflows/master-build.yml
  .github/workflows/pr-validation.yml
  go.sum
Labels: approved, lgtm, size/S

#319 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#320 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#322 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/M, lgtm

#323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#324 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S
