Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2022-03, with the labels that each got.

#245 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#247 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#248 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#250 Fix unicode character problem
  test/config/100-strimzi-cluster-operator-0.23.0.yaml
Labels: approved, size/XS, lgtm

#249 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/M, lgtm

#251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#252 Update sponsoring WG
  README.md
Labels: approved, size/XS, lgtm

#253 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#254 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#256 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#257 :broom: drop support for AWS SQS Source
  README.md
  go.mod
  go.sum
  pkg/reconciler/awssqs/awssqs.go
  pkg/reconciler/keda/annotations.go
  pkg/reconciler/keda/resources.go
  pkg/reconciler/source/source.go
  third_party/VENDOR-LICENSE/knative.dev/eventing-awssqs/pkg/apis/sources/v1alpha1/LICENSE
  vendor/knative.dev/eventing-awssqs/AUTHORS
  vendor/knative.dev/eventing-awssqs/LICENSE
  vendor/knative.dev/eventing-awssqs/pkg/apis/sources/v1alpha1/aws_sqs_types.go
  vendor/knative.dev/eventing-awssqs/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing-awssqs/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing-awssqs/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, kind/removal

#259 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#258 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#260 Adding code of conduct to reference knative/community's CoC
  code-of-conduct.md
Labels: approved, size/M, lgtm

#262 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#264 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm
