Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2023-11, with the labels that each got.

#412 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  third_party/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#413 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#418 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#420 Make SECURITY.md consistent
  SECURITY.md
Labels: approved, size/XS, lgtm

#421 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/state/timings.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#422 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/M, lgtm

#423 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, skip-review

#424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_lifecycle.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/subscribable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
