Repository knative-extensions/eventing-autoscaler-keda, pull requests merged in 2025-04, with the labels that each got.

#559 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#560 Migrate golanglint-ci config to v2
  .golangci.yaml
Labels: approved, lgtm, size/S

#561 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#562 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#564 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#565 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL
